language: ruby
env:
  - NACRE_USER_ID='test_user_id' NACRE_EMAIL='testuser@example.com' NACRE_PASSWORD='123456'
script:
  - bundle exec rspec
rvm:
  - 2.1.0
  - jruby-19mode
branches:
  only:
    - master
notifications:
  email:
    - nacre@allolex.net
